name: test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/fastify-graphql

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 16.x

      - name: Install modules
        run: yarn
        working-directory: ${{ env.working-directory }}

      - run: yarn build
      # run the migration in the test database
      - run: yarn db:push
      - run: yarn test

  # deploy:
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/master' # Only deploy master
  #   needs: test
  #   steps:
  #     - uses: actions/checkout@v2
